xcopy /s /y RuntimeLibs\x64\SDL2.dll %1
xcopy /s /y RuntimeLibs\x64\SDL2_image.dll %1
xcopy /s /y RuntimeLibs\x64\libpng16-16.dll %1
xcopy /s /y RuntimeLibs\x64\SDL2_ttf.dll %1
xcopy /s /y RuntimeLibs\x64\libfreetype-6.dll %1
xcopy /s /y RuntimeLibs\x64\zlib1.dll %1
xcopy /s /y RuntimeLibs\x64\portaudio_x64.dll %1
xcopy /s /y RuntimeLibs\x64\libsndfile-1.dll %1
xcopy /s /y RuntimeLibs\x64\ucrtbased.dll %1
